In [1]:
import numpy as np 

In [12]:
help(np.sort)


Help on function sort in module numpy:

sort(a, axis=-1, kind='quicksort', order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. Default is 'quicksort'.
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A single field can
        be specified as a string, and not all fields need be specified,
        but unspecified fields will still be used, in the order in which
        they come up in the dtype, to break ties.
    
    Returns
    -------
    sorted_array : ndarray
        Array of the same type and shape as `a`.
    
    S

In [13]:
np.sort(["hh",1000,1])

array(['1', '1000', 'hh'], dtype='<U4')

In [14]:
A=[7,6,4,2]

In [15]:
A.sort()

In [16]:
A

[2, 4, 6, 7]

In [22]:
A=np.arange(1,101)

In [23]:
A

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [24]:
np.random.uniform(-1,1,2)

array([-0.38959977,  0.25818537])

In [43]:
N=100
C=0


for i in range(N):
    x = np.random.uniform (-1,1,2)
    r= np.sqrt(x[0]**2 + x[1]**2)
    
    if r< 1 :
        C +=1
        ratio=(4*C)/N
print("ratio=",ratio)


ratio= 3.16


In [44]:
N=1000
C=0


for i in range(N):
    x = np.random.uniform (-1,1,2)
    r= np.sqrt(x[0]**2 + x[1]**2)
    
    if r< 1 :
        C +=1
        ratio=(4*C)/N
print("ratio=",ratio)


ratio= 3.184


In [45]:
N=10000
C=0


for i in range(N):
    x = np.random.uniform (-1,1,2)
    r= np.sqrt(x[0]**2 + x[1]**2)
    
    if r< 1 :
        C +=1
        ratio=(4*C)/N
print("ratio=",ratio)


ratio= 3.138


In [46]:
N=100000
C=0


for i in range(N):
    x = np.random.uniform (-1,1,2)
    r= np.sqrt(x[0]**2 + x[1]**2)
    
    if r< 1 :
        C +=1
        ratio=(4*C)/N
print("ratio=",ratio)


ratio= 3.14064


In [50]:
A= 50 +np.random.randn (100,3)
pearsoncorr =np.corrcoef(A[:,0],A[:,1])
corcoef= pearsoncorr[0,1]

print(pearsoncorr)
print(corcoef)

[[1.         0.06153336]
 [0.06153336 1.        ]]
0.06153336399617433


In [51]:
plt.plot(A[:,0],A[:,1])
plt.show()

NameError: name 'plt' is not defined

In [59]:
plotplot().axis?

Object `axis` not found.


In [ ]:
plotplot().axis