In [1]:
import numpy as np

In [3]:
#dir(np)

In [4]:
np.array?

In [6]:
# a basic way to create an array---where i know the values already
v = np.array([-2, 4, 8])

In [7]:
print(v)

[-2  4  8]


In [8]:
# see dimensionality of a 1D array:
len(v)

3

In [12]:
# note: for a 1D array of length N, the maximum index to use is: N-1
v[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [17]:
type(v[0])

numpy.int64

In [14]:
import sys
sys.version

'3.7.9 (default, Aug 31 2020, 12:42:55) \n[GCC 7.3.0]'

In [18]:
# python CHOOSES a type, based on my inputs here
# it CHOOSES a type with the largest umbrella of values needed
w = np.array([-2., 4, 8])

In [21]:
type(w[2])

numpy.float64

In [22]:
w[1]

4.0

In [23]:
# THIS will never happen again
x = np.array(['-2.', 4, 8])

In [26]:
type(x[1])

numpy.str_

In [27]:
np.array?

In [28]:
# let's add a KWARG to specify datatype of each element explicitly
y = np.array([-2., 4, 8], dtype=complex)

In [29]:
y

array([-2.+0.j,  4.+0.j,  8.+0.j])

In [30]:
type(y[0])

numpy.complex128

In [33]:
z = np.array([-2., 0, 8], dtype=bool)

In [34]:
z

array([ True, False,  True])

In [35]:
v

array([-2,  4,  8])

In [36]:
# i can reassign any element
v[1] = 1000

In [37]:
v

array([  -2, 1000,    8])

In [41]:
# no, the array is REALLY fixed about having 1 element type constant
v[2] = 1.2345

In [42]:
v

array([  -2, 1000,    1])

In [43]:
# other ways to make arrays
# we might want an array of all zeros
np.zeros?

In [46]:
A = np.zeros(10, dtype=int)

In [50]:
type(A[10])

IndexError: index 10 is out of bounds for axis 0 with size 10

In [51]:
A

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
# in math, we can create a vector v \in R^3---only declaring it, not 
# giving it values

# in prog, whenever we make an array, we have to BOTH declare it
# (dimension and element type) AND initialize it (give each ele a value)

# ZEROS are a useful default value for filling in later

In [53]:
type(A)

numpy.ndarray

In [54]:
len(A)

10

In [55]:
# can also be useful for INITIALIZING
np.ones?

In [56]:
# we can make arrays of evenly spaced elements across an interval
np.arange?

In [57]:
# START, the STOP, and the STEP
np.arange(10)   # STOP = 10, def START = 0, STEP = 1, interval = [0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# 'start' is an OPTIONAL ARGUMENT BY POSITION
np.arange(3, 10)  # [3, 10), step=1

array([3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(3, 10, 0.5) # [3, 10), step=0.5

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. ,
       9.5])

In [61]:
# can have negative step---prob want start > stop
np.arange(10, 3, -0.5) # [10, 3), step=-0.5

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5])

In [66]:
B = np.arange(3, 12347621)  # step = 1
len(B)

# there is a relation among: start, stop and N (number of elements) 
# and step

# N = (stop - start)/step ... with caveat for weird step, might
# need int() or rounding to int....

12347618

In [69]:
# the above formula works with even neg step
C = np.arange(10, 3, -0.5)
len(C)

17

In [71]:
(3-10)/-0.43

16.27906976744186

In [76]:
D = np.arange(3, 12) 
D

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
# Python treats a NEGATIVE INDEX "-2" like "N-2", 
# where N is len of array
i = 5
N = len(D)
D[-i] == D[N-i]

True

In [94]:
# sometimes we want a SUBSET of values from an array
# there is SLICING notation/syntax in Python
print(D)
D[1:4]    # i can specify a half open interval [1, 4)

# ***from here on out, MOST intervals in Python are half-open

[ 3  4  5  6  7  8  9 10 11]


array([4, 5, 6])

In [97]:
D[2:6]    # specify start:stop

array([5, 6, 7, 8])

In [100]:
# i can specify the start as 0, OR leave it out bc it is default
D[:4]

array([3, 4, 5, 6])

In [101]:
# i can specify a stop, or leave it bc the default stop is: N
D[4:]

array([ 7,  8,  9, 10, 11])

In [106]:
D[3:8:2]   # can specify a STEP size through the array

array([ 6,  8, 10])

In [107]:
D

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [112]:
D[::2]

array([ 3,  5,  7,  9, 11])

In [114]:
# nb: str have all the same indexing abilities
s = "hello, i am a string"


In [120]:
s[::3]

'hl aatn'

In [121]:
# one important diff between str and arr:
# array are MUTABLE (I can reassign elements)
# str are NOT MUTABLE (I cannot reassign elements)
s[3] = 'J'

TypeError: 'str' object does not support item assignment

In [124]:
D[::100000]

array([3])

In [125]:
D

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])