In [1]:
import numpy as np


In [3]:
np.array([[4,5,6],[7,8,9]])

array([[4, 5, 6],
       [7, 8, 9]])

In [6]:
M=np.array([[4,5,6],[7,8,9]])

In [10]:
S=np.shape(M)
S

(2, 3)

In [12]:
#sidenote: a new type can contain many elements: TUPLE
#           an important property is that it is IMMUTABLE
#           open/close is: (,,,,,)
type(S)

tuple

In [13]:
print (S[0], S[1])

2 3


In [14]:
M

array([[4, 5, 6],
       [7, 8, 9]])

In [15]:
#selecting element from an ndarray
#a multdim array is an array of arrays 
M[0]

array([4, 5, 6])

In [17]:
# selecting a specific element we have M[row,column]
M[0,2]

6

In [18]:
M[1,1]

8

In [19]:
M[1,1:3]

array([8, 9])

In [21]:
M[1,1]

8

In [22]:
M[::]

array([[4, 5, 6],
       [7, 8, 9]])

In [23]:
M[:,1:]

array([[5, 6],
       [8, 9]])

In [24]:
M[:,1]

array([5, 8])

In [25]:
M[:,:2]

array([[4, 5],
       [7, 8]])

In [31]:
M[0:2,0]

array([4, 7])

In [32]:
B=np.array([3,2,1])

In [33]:
B

array([3, 2, 1])

In [34]:
np.shape(B)

(3,)

In [39]:
#initialize C:
C=np.zeros(2)

for i in range(3):
    C[0]+=M[0,i]*B[i]
    C[1]+=M[1,i]*B[i]
print(C)

[28. 46.]


In [43]:
C=np.zeros(2)

for j in range(2):
    for i in range(3):
        C[j]+=M[j,i]*B[i]
print(C)

[28. 46.]


In [48]:
# recall dot product 
u=np.array([4,5,6])
v=np.array ([7,8,9])
b=np.array([3,2,1])
n=len(u)

c=0
d=0

for i in range(n):
    c+=u[i]*b[i]
    d+=v[i]*b[i]
print(c)
print(d)


28
46


In [49]:
# NEW MARIX

In [52]:
X=np.array([2,3,4,5])
Y=np.array([[-1,1],[2,-2],[-3,3],[4,-4]])

Z=np.zeros(2)

for i in range(4):
    Z[0]+= X[i]*Y[i,0]
    Z[1]+= X[i]*Y[i,1]

print(Z)

[ 12. -12.]


In [55]:
X=np.array([2,3,4,5])
Y=np.array([[-1,1],[2,-2],[-3,3],[4,-4]])

Nrow, Ncol=np.shape(Y)
print("Nrow,Ncol =", Nrow,Ncol)
Z=np.zeros(2)


for j in range(2):
    for i in range(4):
        Z[j]+= X[i]*Y[i,j]

print(Z)

Nrow,Ncol = 4 2
3 1
[ 12. -12.]
