In [1]:
import numpy as np


In [2]:
#dir

In [3]:
np.array?

In [9]:
# a basic way to create an array,,, where i know the value already
v = np.array([-2, 4, 8])
print(v)

[-2  4  8]


In [10]:
# see dimmension of a ID array:
len(v)

3

In [11]:
type(v[0])

numpy.int64

In [12]:
import sys
sys.version

'3.7.3 (default, Jan 22 2021, 20:04:44) \n[GCC 8.3.0]'

In [13]:
type(v[1])

numpy.int64

In [14]:
type(v[2])

numpy.int64

In [15]:
# python CHOOSES a type, based on my input here
#it CHOOSES type with  the largest umbrella of values
w = np.array([-2. , 4, 8])

In [16]:
w[0]

-2.0

In [17]:
w[1]

4.0

In [19]:
w[2]

8.0

In [20]:
type(w[0])

numpy.float64

In [21]:
len(w)

3

In [22]:
print(w)

[-2.  4.  8.]


In [23]:
np.array?

In [24]:
# lets add a KWARG to specify datatype 
y = np.array([-2. , 4, 8], dtype=complex)

In [25]:
y

array([-2.+0.j,  4.+0.j,  8.+0.j])

In [28]:
type(y[0])

numpy.complex128

In [36]:
v = np.array([-2 , 4, 8])

In [37]:
v

array([-2,  4,  8])

In [38]:
# i can assign any element
v[1]= 1000

In [39]:
v

array([  -2, 1000,    8])

In [41]:
type(v[1])

numpy.int64

In [42]:
#other ways to make arrays
#we might want an array of all zeros
np.zeros?

In [46]:
A=np.zeros(10, dtype=int)

In [47]:
A

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
type(A)

numpy.ndarray

In [49]:
#in math we can create a vector v in R^3... only declearing it, not 
#giving it values 
#in prog whenever we make an array we have BOTH to declare it
#(dimension)
len(A)

10

In [50]:
z=np.zeros(100, dtype=int)

In [52]:
print(z)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [53]:
# can also be useful fo INNITIALIZING 
np.ones?

In [55]:
#we can make arrays of  evenly spaced elements across intervals 
np.arange?

In [56]:
#START, STOP, and the STEP
np.arange(10)   #STOP = 10, def START = 0, STEP=1, interval = [0,10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# 'start' is an OPTIONAL ARGUMENT BY POSITION
np.arange (3,10)  #[3,10), step =1

array([3, 4, 5, 6, 7, 8, 9])

In [59]:
# 'start' is an OPTIONAL ARGUMENT BY POSITION
np.arange (3,10, 0.5)  #[3,10), step =0.5

array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. ,
       9.5])

In [60]:
# 'start' is an OPTIONAL ARGUMENT BY POSITION
np.arange (3,10, 0.00005)  #[3,10), step =0.00005

array([3.     , 3.00005, 3.0001 , ..., 9.99985, 9.9999 , 9.99995])

In [61]:
np.arange (10, 3, -0.5)  

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5])

In [62]:
B=np.arange (3,10)  #step =1
len(B)

#there is a relation among: start, stop and N (number of elements)
# and stop

# N = int((stop-start)/step)

7

In [63]:
c= np.arange (10, 3, -0.5) 
len(c)

14

In [65]:
D= np.arange(3, 12)
D

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
D[-1]

11

In [68]:
D[-2]

10

In [69]:
#python treats a NEGATIVE INDEX "2" like "N-2",
#where N is the len of array
i= 5
N = len(D)
D[i]==D[N-i]


False

In [72]:
#sometimes we want a subset of values 
print(D)
D[1:4]  #i can specify a half open interval [1, 4]

[ 3  4  5  6  7  8  9 10 11]


array([4, 5, 6])

In [73]:
D[2:6] #specify start:stop

array([5, 6, 7, 8])

In [74]:
# i can specify the start as 0, OR leave it out be the default 
D[:4]

array([3, 4, 5, 6])

In [75]:
#i can specify a stop, or leave it the stop is : n
D[4:]

array([ 7,  8,  9, 10, 11])

In [76]:
D[3:8:2] #can specify a STEP size through 

array([ 6,  8, 10])

In [77]:
D[::2]

array([ 3,  5,  7,  9, 11])

In [78]:
#nb: str have all the same indexing abilities
s = "hello, i am a string"

In [79]:
s[0]

'h'

In [81]:
s[:5]

'hello'

In [85]:
s[6:]

' i am a string'