In [7]:
#Arrays, indexing 

import numpy as np

#NUMBER ONE
v=np.array([4,5,6]) #array of known values
v
print(v)

[4 5 6]


In [6]:
v[0]

4

In [8]:
type(v)

numpy.ndarray

In [11]:
type(v[0])

numpy.int64

In [12]:
v[0]=-100

In [13]:
v

array([-100,    5,    6])

In [16]:
v[1]=99.99

In [17]:
v

array([-100,   99,    6])

In [18]:

len(v)

3

In [19]:
type(v[2])

numpy.int64

In [21]:
#NUMBER TWO

z=np.zeros(6)
z

array([0., 0., 0., 0., 0., 0.])

In [22]:
len(z)

6

In [29]:
x=np.zeros(9, dtype=bool)
x

array([False, False, False, False, False, False, False, False, False])

In [30]:
p=np.zeros(9, dtype=complex)
p

array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j,
       0.+0.j])

In [31]:
type(z)

numpy.ndarray

In [32]:
type(z[1])

numpy.float64

In [33]:
#NUMBER THREE

N1 = np.ones(8)                   # def: dtype=float
N2 = np.ones(4, dtype=bool)
N3 = np.ones(6, dtype=complex)

print(N1)
print(N2)
print(N3)

[1. 1. 1. 1. 1. 1. 1. 1.]
[ True  True  True  True]
[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]


In [34]:
D1 = np.arange(10)                          # def: start = 0, step = 1
D2 = np.arange(-4, 8)                       # def: step = 1
D3 = np.arange(-15, 15, 3)                  # no default
D4 = np.arange(start=-15, stop=15, step=3)  # no default, all keyword args
print(D1)
print(D2)
print(D3)
print(D4)

[0 1 2 3 4 5 6 7 8 9]
[-4 -3 -2 -1  0  1  2  3  4  5  6  7]
[-15 -12  -9  -6  -3   0   3   6   9  12]
[-15 -12  -9  -6  -3   0   3   6   9  12]


In [37]:
#NUMBER FOUR 
L1 = np.linspace(10, 20)          # use default num value
L2 = np.linspace(-2, 2) 
L3= np.linspace(-2, 2, num=11)   # specify num
print(L1)
print(L2)
print(L3)

[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]
[-2.         -1.91836735 -1.83673469 -1.75510204 -1.67346939 -1.59183673
 -1.51020408 -1.42857143 -1.34693878 -1.26530612 -1.18367347 -1.10204082
 -1.02040816 -0.93877551 -0.85714286 -0.7755102  -0.69387755 -0.6122449
 -0.53061224 -0.44897959 -0.36734694 -0.28571429 -0.20408163 -0.12244898
 -0.04081633  0.04081633  0.12244898  0.20408163  0.28571429  0.36734694
  0.44897959  0.53061224  

In [43]:
# If num = 51, then:
#
#   step = (20 - 10)/ (51 -1)
#        = 10/50
#        = 0.2
#
# ... which seems like a nice round number to me!

# The step should be the difference between any two neighboring element
# values, by definition.  So, any of the following should work:
print(L1[1] - L1[0])
print(L1[2] - L1[1])
print(L1[18] - L1[17])
# ... etc., and similarly for any other array.  We just have to make sure
# that the indices we use are within the bounds of the array---so I would
# generally pick the first indices in the array (*if* its length is 2 or
# greater, which might not always be the case!  We might not have a step
# size then to estimate)

# Note that there might be tiny, rounding/truncation error differences at
# the level of decimal precision.


0.204081632653061
0.204081632653061
0.204081632653061


In [44]:
print(L2[1] - L2[0])

# ... the output of the above is not 0.4, like I expected but instead:
# 0.3999999999999999.

# The order of difference is 10**-16, which is tiny, and it seems like
# a case of floating point error.  Specifically, this might be due to the
# fact that Python is using binary numbers internally for calculations (not
# decimals, like we use), and we saw earlier that there is not exact binary
# representation for 0.1, 0.2, 0.3 and 0.4.  (There is for 0.5, though.)
# Again, this is why we wouldn't want to test for exact equality with floats.

0.08163265306122458
