In [8]:
#BOOLEAN

True and False


False

In [2]:
1 and 2

2

In [3]:
2 and 3 # the and looks for something that gives false and if does not find it, it returns the second 

3

In [4]:
bool(' ')

True

In [5]:
bool('hi')

True

In [7]:
-10 and 'banana'

'banana'

In [9]:
0 and 1

0

In [10]:
0 or 1

1

In [11]:
2 or 3

2

In [12]:
bool(0)

False

In [13]:
not True or True

True

In [14]:
not False or True 

True

In [15]:
False == True 

False

In [16]:
False != True

True

In [17]:
not 3

False

In [19]:
not 3==4 #the equal sihm is checked first before "not"

True

In [20]:
1==True

True

In [24]:
bool(100) ==True

True

In [26]:
#MENBERSHIP

#RHS: something collection(str,array,etc..)
#LHS: something to check  for being "in" that collection 

'today' in "today is thursday at AIMS"

True

In [27]:
import numpy as np


In [31]:
3 in np.arange(10)

True

In [29]:
3.0 ==3

True

In [32]:
#CONDITIONS

In [34]:
height = 6.1

if height > 6:                       #here the statement "height>6" is true and  you are tall is printed
    print("you are tall")
    
print("thats is all")
    

you are tall
thats is all


In [37]:
height = 6.1

if height > 6:              #this was true so it never printed else            
    print("you are tall")
    print("you are tall")
    print("you are tall")
else:
    print("you are perfectly heighted")
    
print("thats is all")

you are tall
you are tall
you are tall
thats is all


In [38]:
height = 6.1

if height < 6:                         
    print("you are tall")
    print("you are tall")
    print("you are tall")
else:
    print("you are perfectly heighted")
    
print("thats is all")

you are perfectly heighted
thats is all


In [40]:
height = 6.1

if height > 6:                         
    print("you are tall")
    print("you are tall")
    print("you are tall")                         
elif 6>= height >3:
    print("i hope you are good at football")
else:
    print("you are perfectly heighted")
    
print("thats is all")

you are tall
you are tall
you are tall
thats is all


In [41]:
height = 5

if height > 6:                         
    print("you are tall")
    print("you are tall")
    print("you are tall")
elif 6>= height >3:
    print("i hope you are good at football")
else:
    print("you are perfectly heighted")
    
print("thats is all")

i hope you are good at football
thats is all


In [43]:
height = 6.1

if height > 5:                         
    print("you are tall")
    print("you are tall")               #here python as checked the first condition and it is true so it
    print("you are tall")               # even though elif is also true
elif 6>= height >3:
    print("i hope you are good at football")
else:
    print("you are perfectly heighted")
    
print("thats is all")

you are tall
you are tall
you are tall
thats is all


In [44]:
height = 5

if height > 6:                         
    print("you are tall")
    print("you are tall")
    print("you are tall")
elif 6>= height >3:
    print("i hope you are good at football")
else:
    print("you are perfectly heighted")
    
print("thats is all")

ghfhfjh


In [48]:
var = np.arange(-6,6)

In [49]:
print(var)

[-6 -5 -4 -3 -2 -1  0  1  2  3  4  5]


In [50]:
var[-3]

3

In [52]:
var[2:4] #half-interval [2,5]

array([-4, -3])

In [53]:
var[:5]   #default start is 0

array([-6, -5, -4, -3, -2])

In [54]:
var[5:]  #default end is N

array([-1,  0,  1,  2,  3,  4,  5])

In [55]:
var[2:9:2]   #[start:stop:step]

array([-4, -2,  0,  2])

In [57]:
var[-2]  #it starts from the back

4

In [58]:
var[-1::-1]

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3, -4, -5, -6])