In [2]:
import numpy as np

In [43]:
aMat=np.ones((9,9),dtype=int)*2
print('aMat=',aMat)                                                ##5b

aMat= [[2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2]]


In [42]:
dMat=np.array([  [13,-1,5],[-22,10,-87]]) ##5d
print('dMat=',dMat)


dMat= [[ 13  -1   5]
 [-22  10 -87]]


In [41]:
bMat=np.diag([1,2,3,4,5,4,3,2,1])   
print('bMat=', bMat)                                          ##5b

bMat= [[1 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0]
 [0 0 0 4 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 4 0 0 0]
 [0 0 0 0 0 0 3 0 0]
 [0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 1]]


In [40]:
cMat=np.arange(100).reshape((10,10)).transpose()
print('cMat=', cMat)                                                    ##5c

cMat= [[ 0 10 20 30 40 50 60 70 80 90]
 [ 1 11 21 31 41 51 61 71 81 91]
 [ 2 12 22 32 42 52 62 72 82 92]
 [ 3 13 23 33 43 53 63 73 83 93]
 [ 4 14 24 34 44 54 64 74 84 94]
 [ 5 15 25 35 45 55 65 75 85 95]
 [ 6 16 26 36 46 56 66 76 86 96]
 [ 7 17 27 37 47 57 67 77 87 97]
 [ 8 18 28 38 48 58 68 78 88 98]
 [ 9 19 29 39 49 59 69 79 89 99]]


In [39]:
bvec=np.arange(5,-5.2,-0.2)                    ##4b
print('bvec=',bvec)

bvec= [ 5.0000000e+00  4.8000000e+00  4.6000000e+00  4.4000000e+00
  4.2000000e+00  4.0000000e+00  3.8000000e+00  3.6000000e+00
  3.4000000e+00  3.2000000e+00  3.0000000e+00  2.8000000e+00
  2.6000000e+00  2.4000000e+00  2.2000000e+00  2.0000000e+00
  1.8000000e+00  1.6000000e+00  1.4000000e+00  1.2000000e+00
  1.0000000e+00  8.0000000e-01  6.0000000e-01  4.0000000e-01
  2.0000000e-01 -4.4408921e-15 -2.0000000e-01 -4.0000000e-01
 -6.0000000e-01 -8.0000000e-01 -1.0000000e+00 -1.2000000e+00
 -1.4000000e+00 -1.6000000e+00 -1.8000000e+00 -2.0000000e+00
 -2.2000000e+00 -2.4000000e+00 -2.6000000e+00 -2.8000000e+00
 -3.0000000e+00 -3.2000000e+00 -3.4000000e+00 -3.6000000e+00
 -3.8000000e+00 -4.0000000e+00 -4.2000000e+00 -4.4000000e+00
 -4.6000000e+00 -4.8000000e+00 -5.0000000e+00]


In [3]:
aVec=np.array([3.14, 15, 9, 26]) ##4a
print('aVec=',aVec)

aVec= [ 3.14 15.    9.   26.  ]
