In [2]:
v =3
v+=3

In [3]:
v

6

In [4]:
v= 5 + 2j
k = 5+3j * 5+ 3j


g= v+k

In [5]:
g

(10+20j)

In [6]:
k = 5+3j * 5+ 3j

In [7]:
k

(5+18j)

In [10]:
v  = 2
v **= -2

In [11]:
v

0.25

In [14]:
xy =  True

In [15]:
xy

True

In [16]:
  5 + xy

6

In [17]:
int_ =6

In [18]:
num@int = int(5.5)

SyntaxError: can't assign to operator (<ipython-input-18-1b9c90d769ca>, line 1)

In [19]:
"i my name is eugine"

'i my name is eugine'

In [20]:
print("i my name is eugine")

i my name is eugine


In [22]:
25 * 17.3
x = 45 + 3j
200 - (95 % 17) / 0.0001
'''sawubona'''


'sawubona'

In [24]:
x = 5

print("I am x years older than my immediate junior brother")
print("I am" + str(x) + "years older than my immediate junior brother")
print("I am" + 'x' + "years older than my immediate junior brother")

I am x years older than my immediate junior brother
I am5years older than my immediate junior brother
I amxyears older than my immediate junior brother


In [25]:
print(5*"hello")

hellohellohellohellohello


In [36]:
input()

6


'6'

In [27]:
float ("5")

5.0

In [38]:
v = input()
v = float (v)
print(v)

5
5.0


In [33]:
float (input(True))

True4


4.0

In [37]:
v = input()

8


In [41]:
v = input("Enter your name :")
print("Hello", v)

Enter your name :eugine
Hello eugine


In [43]:
num1=int(input("num1"))
num2=int(input("num2"))
num3=int(input("num3"))
print(num1)
print(num2)
print(num3)
print("Average=", (num1 + num2 + num3)/3)

num11
num22
num33
1
2
3
Average= 2.0


In [46]:
q=int(input(" t-shirt:"))
p=int(input("Price:$"))
print("Total:", q*p)

 t-shirt:10
Price:$150
Total: 1500


In [49]:
sec=int(input())
print("seconds:", sec)
print("minutes:", sec /60 )
print("hours:",sec/3600)

400
seconds: 400
minutes: 6.666666666666667
hours: 0.1111111111111111


In [50]:
import math

In [51]:
y= math.tan ((math.pi)**2)

In [52]:
y

0.47669014603118814

In [68]:
y=math.ceil(6)

In [69]:
y

6

In [79]:
a=int(input("the value of a is:"))
y=(math.cos(a)*math.log10 (1 + a**2))/(1+ (math.e)** -a)
print(y)

the value of a is:56
2.9832964942968694


In [86]:
import random

In [92]:
y= random.random()

In [93]:
ry

0.7716417515829966

In [97]:
math.atan(7)

1.4288992721907328

In [98]:
math.atan2(4,9)

0.4182243295792291

In [99]:
math.log(100,10)

2.0

In [101]:
import numpy as np

In [104]:
np.log(100)

4.605170185988092

In [105]:
import random

In [111]:
np.random.randint(-5,5)

1

In [112]:
False * True

0

In [114]:
'here'in 'there are people'

True

In [115]:
a=56
b=12
(-abs(b-a) > 0 or b-a > 0 ) or (a//b == 4 and not (a/b == 4))


True

In [116]:
x = 3
if x > 25:
    print("This number is big!")
    print("Where did you find it?")
print(x)

3


In [117]:
x = 3
if x > 25:
    print("This number is big!")
elif x < 10:
    print("This number is small!")
print(x)

This number is small!
3


In [118]:
""

''

In [119]:
v=99
v+=45
v=12
v-=5

In [120]:
v

7

In [121]:
import numpy as np

In [122]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [123]:
5%3

2

In [124]:
5//3

1

In [125]:
(246897531%1000)//100

5

In [129]:
v=np.array ([2,3,5])

In [130]:
v

array([2, 3, 5])

In [131]:
v[1]=900

In [132]:
v

array([  2, 900,   5])

In [135]:
v=np.linspace(2,8)
v

array([2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
       2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
       3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
       3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
       4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551,
       5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
       5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
       6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
       6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
       7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ])

In [136]:
len(v)

50

In [137]:
A = np.array([0, 5, 10, 15, 20, 25, 30])

In [138]:
type(A)

numpy.ndarray

In [139]:
p= np.linspace(-15,15, dtype=int)

In [140]:
p

array([-15, -14, -13, -13, -12, -11, -11, -10, -10,  -9,  -8,  -8,  -7,
        -7,  -6,  -5,  -5,  -4,  -3,  -3,  -2,  -2,  -1,   0,   0,   0,
         0,   1,   2,   2,   3,   3,   4,   5,   5,   6,   7,   7,   8,
         8,   9,  10,  10,  11,  11,  12,  13,  13,  14,  15])

In [141]:
len(p)

50

In [143]:
t= np. arange(-15,15.2,0.2)
t

array([-1.50000000e+01, -1.48000000e+01, -1.46000000e+01, -1.44000000e+01,
       -1.42000000e+01, -1.40000000e+01, -1.38000000e+01, -1.36000000e+01,
       -1.34000000e+01, -1.32000000e+01, -1.30000000e+01, -1.28000000e+01,
       -1.26000000e+01, -1.24000000e+01, -1.22000000e+01, -1.20000000e+01,
       -1.18000000e+01, -1.16000000e+01, -1.14000000e+01, -1.12000000e+01,
       -1.10000000e+01, -1.08000000e+01, -1.06000000e+01, -1.04000000e+01,
       -1.02000000e+01, -1.00000000e+01, -9.80000000e+00, -9.60000000e+00,
       -9.40000000e+00, -9.20000000e+00, -9.00000000e+00, -8.80000000e+00,
       -8.60000000e+00, -8.40000000e+00, -8.20000000e+00, -8.00000000e+00,
       -7.80000000e+00, -7.60000000e+00, -7.40000000e+00, -7.20000000e+00,
       -7.00000000e+00, -6.80000000e+00, -6.60000000e+00, -6.40000000e+00,
       -6.20000000e+00, -6.00000000e+00, -5.80000000e+00, -5.60000000e+00,
       -5.40000000e+00, -5.20000000e+00, -5.00000000e+00, -4.80000000e+00,
       -4.60000000e+00, -

In [149]:
z= np.linspace(-3,3,2)
z

array([-3.,  3.])